name: Bug report
description: Report a defect in the Carbon Budget Gate, workbook, or MVP logic
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees:
  - vlad12-k
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide enough detail so it can be reproduced and verified.

  - type: dropdown
    id: area
    attributes:
      label: Affected area
      description: Which part is broken?
      options:
        - GitHub Actions (Carbon Budget Gate)
        - Workbook CSV (Appendix D)
        - CO2e calculator script (calc_co2e.py)
        - Documentation / Appendices
        - Other
    validations:
      required: true

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Describe the problem and the observed behaviour.
      placeholder: "The workflow fails with exit code 1 when..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: "The workflow should pass and show summary metrics..."
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide step-by-step reproduction.
      value: |
        1.
        2.
        3.
      render: bash
    validations:
      required: true

  - type: input
    id: evidence
    attributes:
      label: Evidence link
      description: Paste the GitHub Actions run URL or attach screenshots.
      placeholder: "https://github.com/.../actions/runs/..."
    validations:
      required: false

  - type: textarea
    id: csv_rows
    attributes:
      label: Workbook rows used
      description: Paste the baseline/improved rows from Appendix D CSV.
      render: text
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - GitHub Web UI
        - GitHub Actions runner
        - Codespaces
        - Local machine
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: Quick checks
      description: Confirm these before submitting (helps triage).
      options:
        - label: I verified the latest workflow run (not an old run) and checked the logs.
          required: true
        - label: I confirmed the CSV path is `workbook/appendix-d-baseline-improved.csv`.
          required: true
